"""empty message

Revision ID: 710532550159
Revises: 45032ed90caf
Create Date: 2023-11-15 22:19:42.867230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710532550159'
down_revision = '45032ed90caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('height')

    # ### end Alembic commands ###
