"""empty message

Revision ID: 9f56d8ed040a
Revises: c713c574d16a
Create Date: 2023-11-22 00:37:16.753069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f56d8ed040a'
down_revision = 'c713c574d16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('seeking_description', sa.String(), nullable=True))
        batch_op.drop_column('artist_desc')
        batch_op.drop_column('interest_venue')

    with op.batch_alter_table('Venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('seeking_description', sa.String(), nullable=True))
        batch_op.drop_column('interest_talent')
        batch_op.drop_column('venue_desc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_desc', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('interest_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seeking_talent')

    with op.batch_alter_table('Artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_venue', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('artist_desc', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###
