"""empty message

Revision ID: 6766e4559d0c
Revises: 6e80f7cf65dd
Create Date: 2023-12-31 07:33:44.461147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6766e4559d0c'
down_revision = '6e80f7cf65dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Bookings', schema=None) as batch_op:
        batch_op.alter_column('stylist_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Bookings', schema=None) as batch_op:
        batch_op.alter_column('stylist_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
