"""empty message

Revision ID: 86aca8c65a5a
Revises: 8d102bbe7842
Create Date: 2024-01-06 16:42:53.604116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86aca8c65a5a'
down_revision = '8d102bbe7842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Stylists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Stylists', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
