"""empty message

Revision ID: c3de70299ec2
Revises: b4e88ee4e3ac
Create Date: 2024-01-06 15:05:43.852532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3de70299ec2'
down_revision = 'b4e88ee4e3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Stylists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salon_role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Stylists', schema=None) as batch_op:
        batch_op.drop_column('salon_role')

    # ### end Alembic commands ###
